// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cexhxsjaeunkdvxsdtuc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNleGh4c2phZXVua2R2eHNkdHVjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAwMDI5MDIsImV4cCI6MjA2NTU3ODkwMn0.5sPagJxV_NyBJCTQIQTiR27phm5q7B33sJXgVhVjgyY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);